# -*- coding: utf-8 -*-  
"""
@author: Suibin Sun
@file: cleaner.py
@time: 2018/5/10 21:51
"""

import os
import shutil

base_dir = ''
folder_name = ''


def clean():
    """
    Clean the patch images and folders generated by image_preprocessor.generate_patched()
    :return:
    """
    sets = os.listdir(base_dir)
    total = len(sets)
    count = 1
    for a_set in sets:
        folder_path = os.path.join(base_dir, a_set, folder_name)
        try:
            shutil.rmtree(folder_path)
        except FileNotFoundError:
            print('Directory not found!')
        print('\r', 'removing {0}/{1}'.format(count, total).ljust(20), end='')


if __name__ == '__main__':
    base_dir = 'D:\All_Projects\ML_project\HPA_ieee\data'
    folder_name = 'new'     # edit by yourself
    clean()
